version: "3.9"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fuel-sqlserver-local
    hostname: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "StrongPass!123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sqlserver/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: >
        /opt/mssql-tools/bin/sqlcmd
        -S localhost
        -U sa
        -P StrongPass!123
        -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: fuel-postgres
    hostname: postgres
    ports:
      - "5455:5432"
    environment:
      POSTGRES_DB: ms_fuel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ms_fuel"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  sqlserver_data:
  postgres_data:
