
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5455}/${DB_NAME:ms_fuel}?stringtype=unspecified
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 2000000
      maximum-pool-size: 20 #  cantidad de conexiones dentro del pool: 20 conexiones
      auto-commit: false # el commit es manejado por las transacciones de Spring
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 30000
  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:poc}
        show_sql: true
        ddl-auto: create-drop

  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-docs

swagger:
  info:
    title: Fuel Exemplo
    version: 0.0.1-SNAPSHOT
    description: Api for execute transactions events
  server:
    main:
      url: ${server.servlet.context-path}
      description: API Server

server:
  port: 8080
